version: '3.8'

x-common-volumes: &common-volumes
  - ./:/MoneyPrinterTurbo

networks:
  app-network:
    driver: bridge

services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'moneyprinterturbo-webui'
    expose:
      - '8501'
    command: [
      'streamlit', 'run', './webui/Main.py',
      '--browser.serverAddress=0.0.0.0',
      '--server.enableCORS=True',
      '--browser.gatherUsageStats=False'
    ]
    volumes: *common-volumes
    restart: always
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'moneyprinterturbo-api'
    expose:
      - '8080'
    command: ['python3', 'main.py']
    volumes: *common-volumes
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: 'moneyprinterturbo-nginx'
    ports:
      - '80:80'
    depends_on:
      - webui
      - api
    restart: always
    networks:
      - app-network
    volumes:
      - ./nginx_logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
